# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DarwinniwraD
tagline:             'A web developer'
description:         'Web Developer from Shanghai'
url:                 https://darwinniwrad.github.io/
baseurl:             ''
paginate:            5
avatar:              https://avatars1.githubusercontent.com/u/7356863?v=3&s=40

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# sidebar social Media setting 
footer-links:
  dribbble:
  email:             cliozhl@gmail.com
  facebook:
  flickr:
  github:            DarwinniwraD
  instagram:
  linkedin:          louislzhang
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:           ChangClio
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Custom vars
version:             1.0.0

